export const Tech = [
  {
    id: 1,
    name: "Abhijeet Varma",
    role: "Technical Head",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/Departments/tech/IMG_1498_wtXmCgsX7.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1647284864777&tr=w-1080%2Ch-566%2Cfo-auto",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "S.Adithiya",
    role: "Technical 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/IMG_2358_UQZmlTl9k.JPG?updatedAt=1680475564046",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "Aditiya",
    role: "Technical 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Aditya/IMG_2362_oleBycKbN.JPG?updatedAt=1680475515187",
    form: "javascript:void(0)",
    tar: "_self",
  },
];

export const Board = [
  {
    id: 2,
    name: "Sagar Sharma",
    role: "Vice-Chief",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Sagar/_MG_2473_PNga7udoi.JPG?updatedAt=1680475518799",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 1,
    name: "Sameer Khan",
    role: "Chief",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Sammer/IMG_2324_okNr19HyL.JPG?updatedAt=1680475518944",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Suman Biswas",
    role: "Chief-Advisor",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Suman/IMG_2103__qGLTexzR.JPG?updatedAt=1680475522162",
    form: "javascript:void(0)",
    tar: "_self",
  },
];

export const Event = [
  {
    id: 1,
    name: "Sahithi Devershetty",
    role: "Events Head",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/Departments/Events/Sahithi_Devarashetty_3rd_pmcPIq_4TImk.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1647196134692",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "Manasa ",
    role: "Events 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Manasa/IMG_2316_cEweU26d2.JPG?updatedAt=1680475518373",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Mohammad Fayaz",
    role: "Events 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Fayez/IMG_2099_eNQrp4Aum.JPG?updatedAt=1680475515729",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 4,
    name: "Aashrit",
    role: "Events 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Aashrit/IMG_2354_sGcnpt4Rz.JPG?updatedAt=1680475515216",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 5,
    name: "Sony",
    role: "Events 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Sony/IMG_2321_QmV--8NdJ.JPG?updatedAt=1680475521195",
    form: "javascript:void(0)",
    tar: "_self",
  },
];

export const Market = [
  {
    id: 1,
    name: "Kiranmayi Lanka",
    role: "Marketing Head",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Kiranmai/IMG_2094_ecNP1pFbJ.JPG?updatedAt=1680475515722",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "Sathvik",
    role: "Marketing 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Sathvik/IMG_2118_HJaPCoCVI.JPG?updatedAt=1680475521065",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Sujith",
    role: "Marketing 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Sujith/IMG_2113_o4lVqoApj.JPG?updatedAt=1680475521605",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 4,
    name: "Monish",
    role: "Marketing 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Monish/IMG_2346_VaTAvNYAA.JPG?updatedAt=1680475517985",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 4,
    name: "Vinay",
    role: "Marketing 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Vinay/IMG_2341_dHxt4oWAAw.JPG?updatedAt=1680475522159",
    form: "javascript:void(0)",
    tar: "_self",
  },
];

export const VFX = [
  {
    id: 1,
    name: "Chanakya",
    role: "VFX Head",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Chanakya/20230328011645__MG_2475_17V5_7qq59.JPG?updatedAt=1680475515191",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "Rasool",
    role: "VFX 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Rasool/IMG_2122_gP2NVvohm7.JPG?updatedAt=1680475519253",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Santoshi",
    role: "VFX 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Santoshi/20230328230302__MG_2509_wJH7U-ISw.JPG?updatedAt=1680475520483",
    form: "javascript:void(0)",
    tar: "_self",
  },
];

export const Photo = [
  {
    id: 1,
    name: "Rohan Reddy",
    role: "Head",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Rohan/IMG_2142_OSramRjtpa.JPG?updatedAt=1680475519406",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Madhulika",
    role: "3rd Year",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Madhulika/IMG_2128_4WK67ZC4F.JPG?updatedAt=1680475515723",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "Rishik",
    role: "2nd Year",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Rishik/IMG_20230329_201254_caxXt2d09x.jpg?updatedAt=1680475518973",
    form: "javascript:void(0)",
    tar: "_self",
  },
];

export const Wizards = [
  {
    id: 1,
    name: "Anshitha Adepu",
    role: "Wizards Head",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Anshita/IMG_2312_v_r5VxoKtC.JPG?updatedAt=1680475515229",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "Pavan",
    role: "Wizards 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Pawan/IMG_2109_-dWC6_mLKu.JPG?updatedAt=1680475519407",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Pokshani",
    role: "Wizards 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/Departments/Wiz/pokshani_iPpgSd1yY?updatedAt=1680500701576",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Hamsa",
    role: "Wizards 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Hamsa/IMG_2336_cCqEOzcC9_.JPG?updatedAt=1680475515201",
    form: "javascript:void(0)",
    tar: "_self",
  },
];

export const Stage = [
  {
    id: 1,
    name: "Prasoon Reddy",
    role: "Stage Head",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/Departments/Stage/Prasoon_Reddy_3rd_fXSiXO3Cb.jpeg?updatedAt=1647195674610",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 2,
    name: "Nihal Reddy",
    role: "Stage 3rd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Nihaal/20230328235828__MG_2541_iCHQwZoid.JPG?updatedAt=1680475518642",
    form: "javascript:void(0)",
    tar: "_self",
  },
  {
    id: 3,
    name: "Veda Reddy",
    role: "Stage 2nd Yr",
    desc: " ",
    img: "https://ik.imagekit.io/o3b14qow3gqi/TamV9_Crew/TAM_photos/Veda/IMG_2394_7LVovHNw1O.JPG?updatedAt=1680475522010",
    form: "javascript:void(0)",
    tar: "_self",
  },
];
