export const tech = {
  id: "tech",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Technical Department",
  headline: "TECHIES",
  description:
    "We basically ensure the smooth functioning of technical operations, monitor and evaluate stuff etc." +
    " We lead a path for our content to be displayed on different platforms of web",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/tech_4EjZVL_56qs8.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647426464644",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const marketing = {
  id: "market",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Marketing Department",
  headline: "INFLUENCERS",
  description:
    "We are the voice of Tam and we provide deep insight on various events that we host and organize. We are the reason for many people willing to be part of us.",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/market_OHdNIKXD0.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1647426712917",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const events = {
  id: "evemts",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Events Department",
  headline: "EVENTERS",
  description:
    "We are the ones behind the execution of event which includes organizing, planning etc. " +
    "We host an event in such a way that everyone is attracted and we dedicate ourselves from start to end",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/event_TErj-pxkk.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1647426803182",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const wiz = {
  id: "wiz",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Wizards Department",
  headline: "ECHANTERS",
  description:
    "We are the literary leaders,we takecare of writing all the tricky questions you have to answer and speeches you have to listen",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/wiz_hU6vnfdbgn08.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647426387567",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const photo = {
  id: "photo",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Photography Department",
  headline: "PAPARAZZIS",
  description:
    "We capture the beautiful moments throughout the event and create lifelong memories. We portray the story of event through our pictures. We capture all the smiles and hardwork done behind this success.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/photo_XiBUXB2ZO.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1647426010607 ",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const stage = {
  id: "photo",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Stage Department",
  headline: "STAGEHANDS",
  description:
    "We extend our hand and provide our assistance and expertise in making the event a success. We are always on our toes for helping this run smoothly.",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/styage_DHSY9ZaK3R.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1647425818034",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const vfx = {
  id: "vfx",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "VFX Department",
  headline: "CREATORS",
  description:
    "We work on presenting eye-catching as well as informative content. " +
    "We provide a visual treat to the viewers by enhancing the primary content.",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/vfx_gPeP89cc8.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1647426096185",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const board = {
  id: "board",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "The Board Members",
  headline: "EXECUTIVES",
  description:
    "We are the main pillars of Tam and we work in the direction of making this a success in terms of finance, technicality, etc. " +
    "We inspire and encourage the upcoming members to lead this ahead.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "https://ik.imagekit.io/o3b14qow3gqi/team/board_HDxzu9n5M.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1647426570501",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "events",
  linkS: false,
  linkR: false,
  data: [],
  view: "none",
};

export const advisor = {
  id: "advisor",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Faculty Advisor",
  headline: "E.Sowmya",
  description:
    "Every great organization has a great team and every great teams need a great Advisor. We as a crew at TAM have made it a point to ensure that every event is filled with a great deal of success, in addition to ensuring every participant is able to be served with equal priority. From planning the events to marketing, to making our website, we make sure that we are meeting the needs of every participant.",
  buttonLabel: "Contact Us",
  imgStart: false,
  img: "https://ik.imagekit.io/o3b14qow3gqi/Crew/sss_z642MOd4G.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1647509408608",
  alt: "TAM",
  dark: true,
  primary: true,
  darkText: false,
  to: "/goToGoogle",
  linkS: false,
  linkR: false,
  linkC: false,
  data: [],
  view: "none",
};
